meter1:
  port: /dev/ttyUSB0
  pins:
    10: psutil.sensors_fans()['it8721'][0].current/2000.0 # CPU Fan (2000 rpm max)
    11: psutil.sensors_temperatures()['k10temp'][0].current/70 # CPU Temp (70 degrees max)
meter2:
  port: /dev/ttyUSB1
  pins:
    11: self.avg([(i / 100.) for i in psutil.cpu_percent(self.parent.interval, True)]) # average CPU (Instead of random sampling of cores)